# 此文件需要保密！

development: &default
  site_title: '小莫的小栈'
  site_url: 'http://localhost:3000'
  site_motto: 'stay hungry, stay foolish'
  qq_api_key: '101310369'
  qq_api_secret: 'e4f99aabf6243d1afa64968992ccfcde'
  qq_redirect_uri: 'http://www.msl12.cn/qq_callback'

production:
  <<: *default