development: &default
  site_title: '小莫的小栈'
  site_url: 'http://localhost:3000'
  site_motto: 'stay hungry, stay foolish'
  site_description: 'msl12的个人博客网站，发表个人原创的博客文章'

  # use for QQ login
  qq_api_key: ''
  qq_api_secret: ''
  qq_redirect_uri: ''

production:
  <<: *default
  site_url: 'http://www.msl12.cn'